# Autolinking scripts
require_relative '../node_modules/expo/scripts/autolinking'
require_relative '../node_modules/react-native/scripts/react_native_pods'
require 'json'

# Load Podfile properties
podfile_props = JSON.parse(File.read('Podfile.properties.json')) rescue {}

# Toggle new architecture
new_arch_enabled = podfile_props['newArchEnabled'] == 'true'
ENV['RCT_NEW_ARCH_ENABLED'] = new_arch_enabled ? '1' : '0'

# Set platform and deployment target
platform :ios, podfile_props['ios.deploymentTarget'] || '15.1'
install! 'cocoapods', deterministic_uuids: false

# Prepare React Native project
prepare_react_native_project!

target 'voltuoso' do
  # Use Expo modules
  use_expo_modules!
  
  # Configure native modules
  config = use_native_modules!
  
  # Enable frameworks if configured
  if podfile_props['ios.useFrameworks']
    use_frameworks! linkage: podfile_props['ios.useFrameworks'].to_sym
  end
  
  # Configure React Native
  use_react_native!(
    path: config[:reactNativePath],
    hermes_enabled: podfile_props['expo.jsEngine'] != 'jsc',
    fabric_enabled: new_arch_enabled,
    new_arch_enabled: new_arch_enabled,
    app_path: "#{Pod::Config.instance.installation_root}/..",
    privacy_file_aggregation_enabled: podfile_props['apple.privacyManifestAggregationEnabled'] != 'false'
  )
  
  post_install do |installer|
    # React Native post install
    react_native_post_install(
      installer,
      config[:reactNativePath],
      mac_catalyst_enabled: false,
      ccache_enabled: podfile_props['apple.ccacheEnabled'] == 'true'
    )
    
    # Additional pod target configurations
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        # Set minimum deployment target to match platform requirement
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = podfile_props['ios.deploymentTarget'] || '15.1'
        
        # Disable bitcode (deprecated in Xcode 14)
        config.build_settings['ENABLE_BITCODE'] = 'NO'
        
        # Fix for some common build issues
        config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'YES'
      end
    end
    
    # Handle resource bundle code signing
    installer.pod_targets.each do |pod_target|
      if pod_target.respond_to?(:resource_bundle_targets)
        pod_target.resource_bundle_targets.each do |resource_bundle_target|
          resource_bundle_target.build_configurations.each do |config|
            config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
          end
        end
      end
    end
  end
end