# ios/Podfile

require File.join(
  File.dirname(`node --print "require.resolve('expo/package.json')"`),
  "scripts/autolinking"
)
require File.join(
  File.dirname(`node --print "require.resolve('react-native/package.json')"`),
  "scripts/react_native_pods"
)

platform :ios, '15.1'
install! 'cocoapods', :deterministic_uuids => false

prepare_react_native_project!

target 'Voltuoso' do
  # Pull in all native modules (React Native and Expo)
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    :hermes_enabled => true,
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  use_expo_modules!
end

post_install do |installer|
  # Standard React Native post-install tasks
  react_native_post_install(installer)

  # Disable code signing for resource bundles on Xcode 14+
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
    end
  end
end
